//
//  SearchScreenModels.swift
//  gitHubApi
//
//  Created by Juan Guillermo Quiroga Salamanca on 11/5/19.
//  Copyright (c) 2019 Juan Guillermo Quiroga Salamanca. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Foundation

enum SearchScreen
{
  // MARK: Use cases
  
  enum User
  {
    struct Request
    {
        var userName : String
    }
    struct UserList: Codable {
        let totalCount: Int
        let incompleteResults: Bool
        let items: [Response]

        enum CodingKeys: String, CodingKey {
            case totalCount = "total_count"
            case incompleteResults = "incomplete_results"
            case items
        }
    }
    
    struct Response: Codable {
        let login: String
        let id: Int
        let nodeID: String
        let avatarURL: String
        let gravatarID: String
        let url, htmlURL, followersURL, subscriptionsURL: String
        let organizationsURL, reposURL, receivedEventsURL: String
        let type: String
        let score: Double

        enum CodingKeys: String, CodingKey {
            case login, id
            case nodeID = "node_id"
            case avatarURL = "avatar_url"
            case gravatarID = "gravatar_id"
            case url
            case htmlURL = "html_url"
            case followersURL = "followers_url"
            case subscriptionsURL = "subscriptions_url"
            case organizationsURL = "organizations_url"
            case reposURL = "repos_url"
            case receivedEventsURL = "received_events_url"
            case type, score
        }
    }
    
    struct ViewModel
    {
        var login : String
        var id : Int
        var avatar_url : String
        var html_url : String
        var score : Double
        var repos_url : String
    }
  }
}
