//
//  SearchScreenRouter.swift
//  gitHubApi
//
//  Created by Juan Guillermo Quiroga Salamanca on 11/5/19.
//  Copyright (c) 2019 Juan Guillermo Quiroga Salamanca. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol SearchScreenRoutingLogic
{
   func routeToResults(segue: UIStoryboardSegue?)
}

protocol SearchScreenDataPassing
{
  var dataStore: SearchScreenDataStore? { get }
}

class SearchScreenRouter: NSObject, SearchScreenRoutingLogic, SearchScreenDataPassing
{
  weak var viewController: SearchScreenViewController?
  var dataStore: SearchScreenDataStore?
  
  // MARK: Routing
  
  func routeToResults(segue: UIStoryboardSegue?)
  {
    if let segue = segue {
      let destinationVC = segue.destination as! ResultScreenViewController
      var destinationDS = destinationVC.router!.dataStore!
      passDataToResults(source: dataStore!, destination: &destinationDS)
    }
    else {
      let storyboard = UIStoryboard(name: "Main", bundle: nil)
      let destinationVC = storyboard.instantiateViewController(withIdentifier: "resultScreen") as! ResultScreenViewController
      var destinationDS = destinationVC.router!.dataStore!
      passDataToResults(source: dataStore!, destination: &destinationDS)
      navigateToSomewhere(source: viewController!, destination: destinationVC)
    }
  }

  // MARK: Navigation
  
  func navigateToSomewhere(source: SearchScreenViewController, destination: ResultScreenViewController)
  {
    source.show(destination, sender: nil)
    //source.navigationController?.popViewController(animated: true)
  }
  
  // MARK: Passing data
  
  func passDataToResults(source: SearchScreenDataStore, destination: inout ResultScreenDataStore)
  {
    destination.results = source.results
    print(destination.results.count)
  }
}
