//
//  SearchScreenPresenter.swift
//  gitHubApi
//
//  Created by Juan Guillermo Quiroga Salamanca on 11/5/19.
//  Copyright (c) 2019 Juan Guillermo Quiroga Salamanca. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SearchScreenPresentationLogic
{
  func presentResponse(response: [SearchScreen.User.ViewModel])
  func presentError(error : String)
}

class SearchScreenPresenter: SearchScreenPresentationLogic
{
  weak var viewController: SearchScreenDisplayLogic?
  
  // MARK: Do something
  
  func presentResponse(response: [SearchScreen.User.ViewModel])
  {
  //  print(response)
    viewController?.displayResponse(viewModel: response)
    
  }
    
  func presentError(error: String) {
      viewController?.displayError(error: error)
  }
}
