//
//  SearchScreenInteractor.swift
//  gitHubApi
//
//  Created by Juan Guillermo Quiroga Salamanca on 11/5/19.
//  Copyright (c) 2019 Juan Guillermo Quiroga Salamanca. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SearchScreenBusinessLogic
{
  func doSomething(request: SearchScreen.Something.Request)
}

protocol SearchScreenDataStore
{
  //var name: String { get set }
}

class SearchScreenInteractor: SearchScreenBusinessLogic, SearchScreenDataStore
{
  var presenter: SearchScreenPresentationLogic?
  var worker: SearchScreenWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: SearchScreen.Something.Request)
  {
    worker = SearchScreenWorker()
    worker?.doSomeWork()
    
    let response = SearchScreen.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
