//
//  SearchScreenPresenter.swift
//  gitHubApi
//
//  Created by Juan Guillermo Quiroga Salamanca on 11/5/19.
//  Copyright (c) 2019 Juan Guillermo Quiroga Salamanca. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SearchScreenPresentationLogic
{
  func presentResponse(response: SearchScreen.User.UserList)
  func presentError(error : String)
}

class SearchScreenPresenter: SearchScreenPresentationLogic
{
  weak var viewController: SearchScreenDisplayLogic?
  
  // MARK: Do something
  
  func presentResponse(response: SearchScreen.User.UserList)
  {
  //  print(response)
//
    var itemList : [SearchScreen.User.ViewModel] = []
    for item in response.items{
        let viewModel = SearchScreen.User.ViewModel(login: item.login, id: item.id, avatar_url: item.avatarURL, html_url: item.htmlURL, score: item.score, repos_url: item.reposURL)
        itemList.append(viewModel)
    }
    
    viewController?.displayResponse(viewModel: itemList)
    
  }
    
  func presentError(error: String) {
      viewController?.displayError(error: error)
  }
}
