//
//  DetailScreenPresenter.swift
//  gitHubApi
//
//  Created by Juan Guillermo Quiroga Salamanca on 11/5/19.
//  Copyright (c) 2019 Juan Guillermo Quiroga Salamanca. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DetailScreenPresentationLogic
{
  func presentSomething(response: DetailScreen.Something.Response)
}

class DetailScreenPresenter: DetailScreenPresentationLogic
{
  weak var viewController: DetailScreenDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: DetailScreen.Something.Response)
  {
    let viewModel = DetailScreen.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
