//
//  DetailScreenInteractor.swift
//  gitHubApi
//
//  Created by Juan Guillermo Quiroga Salamanca on 11/5/19.
//  Copyright (c) 2019 Juan Guillermo Quiroga Salamanca. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DetailScreenBusinessLogic
{
  func doSomething(request: DetailScreen.Something.Request)
}

protocol DetailScreenDataStore
{
  //var name: String { get set }
}

class DetailScreenInteractor: DetailScreenBusinessLogic, DetailScreenDataStore
{
  var presenter: DetailScreenPresentationLogic?
  var worker: DetailScreenWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: DetailScreen.Something.Request)
  {
    worker = DetailScreenWorker()
    worker?.doSomeWork()
    
    let response = DetailScreen.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
