//
//  DetailScreenInteractor.swift
//  gitHubApi
//
//  Created by Juan Guillermo Quiroga Salamanca on 11/5/19.
//  Copyright (c) 2019 Juan Guillermo Quiroga Salamanca. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DetailScreenBusinessLogic
{
  func doSomething(request: DetailScreen.Something.Request)
}

protocol DetailScreenDataStore
{
  //var name: String { get set }
  var result : SearchScreen.User.ViewModel{get set}
}

class DetailScreenInteractor: DetailScreenBusinessLogic, DetailScreenDataStore
{
    var result: SearchScreen.User.ViewModel = SearchScreen.User.ViewModel(login: "", id: 0, avatar_url: "", html_url: "", score: 0, repos_url: "")
    
    
  var presenter: DetailScreenPresentationLogic?
  var worker: DetailScreenWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: DetailScreen.Something.Request)
  {
    worker = DetailScreenWorker()
    worker?.doSomeWork()
    
    let response = DetailScreen.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
