//
//  DetailScreenViewController.swift
//  gitHubApi
//
//  Created by Juan Guillermo Quiroga Salamanca on 11/5/19.
//  Copyright (c) 2019 Juan Guillermo Quiroga Salamanca. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DetailScreenDisplayLogic: class
{
  func displaySomething(viewModel: DetailScreen.Something.ViewModel)
}

class DetailScreenViewController: UIViewController, DetailScreenDisplayLogic
{
  var interactor: DetailScreenBusinessLogic?
  var router: (NSObjectProtocol & DetailScreenRoutingLogic & DetailScreenDataPassing)?
  var displayedResutls : [SearchScreen.User.ViewModel] = []
  // MARK: Object lifecycle
  
  override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
  {
    super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    setup()
  }
  
  required init?(coder aDecoder: NSCoder)
  {
    super.init(coder: aDecoder)
    setup()
  }
  
  // MARK: Setup
  
  private func setup()
  {
    let viewController = self
    let interactor = DetailScreenInteractor()
    let presenter = DetailScreenPresenter()
    let router = DetailScreenRouter()
    viewController.interactor = interactor
    viewController.router = router
    interactor.presenter = presenter
    presenter.viewController = viewController
    router.viewController = viewController
    router.dataStore = interactor
  }
  
  // MARK: Routing
  
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    if let scene = segue.identifier {
      let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
      if let router = router, router.responds(to: selector) {
        router.perform(selector, with: segue)
      }
    }
  }
  
  // MARK: View lifecycle
  
  override func viewDidLoad()
  {
    super.viewDidLoad()
    doSomething()
  }
  
  // MARK: Do something
  
  //@IBOutlet weak var nameTextField: UITextField!
    @IBOutlet weak var idLabel: UILabel!
    @IBOutlet weak var loginLabel: UILabel!
    @IBOutlet weak var scoreLabel: UILabel!
    @IBOutlet weak var repoUrlLabel: UILabel!
    
  
  func doSomething()
  {
    let request = DetailScreen.Something.Request()
    interactor?.doSomething(request: request)
    
    if let result = router?.dataStore?.result{
        loadUserData(user: result)
    }
    
  }
  
  func displaySomething(viewModel: DetailScreen.Something.ViewModel)
  {
    //nameTextField.text = viewModel.name
  }
    func loadUserData(user : SearchScreen.User.ViewModel){
        idLabel.text = "\(user.id)"
        loginLabel.text = user.login
        scoreLabel.text = "\(user.score)"
        repoUrlLabel.text = user.repos_url
    }
}
