//
//  ResultScreenInteractor.swift
//  gitHubApi
//
//  Created by Juan Guillermo Quiroga Salamanca on 11/5/19.
//  Copyright (c) 2019 Juan Guillermo Quiroga Salamanca. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ResultScreenBusinessLogic
{
    func listResutls(request: SearchScreen.User.ViewModel)
}

protocol ResultScreenDataStore
{
   var results : [SearchScreen.User.ViewModel]{get set}
    var result : SearchScreen.User.ViewModel{ get set }
}
class ResultScreenInteractor: ResultScreenBusinessLogic, ResultScreenDataStore
{
  var presenter: ResultScreenPresentationLogic?
  var worker: ResultScreenWorker?
  //var name: String = ""
  var results : [SearchScreen.User.ViewModel] = []
  // MARK: Do something
    var result: SearchScreen.User.ViewModel = SearchScreen.User.ViewModel(login: "", id: 0, avatar_url: "", html_url: "", score: 0, repos_url: "")
    
  
  func listResutls(request: SearchScreen.User.ViewModel)
  {
    result = request
    let response = ResultScreen.UserList.Response()
    presenter?.presentSomething(response: response)
  }
}
