//
//  ResultScreenModels.swift
//  gitHubApi
//
//  Created by Juan Guillermo Quiroga Salamanca on 11/5/19.
//  Copyright (c) 2019 Juan Guillermo Quiroga Salamanca. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ResultScreen
{
  // MARK: Use cases
  
  enum UserList
  {
    struct Request
    {
    }
    struct Response
    {
    }
    struct ViewModel
    {
        var login : String
        var id : Int
        var avatar_url : String
        var score : Double
    }
  }
}
