//
//  ResultScreenRouter.swift
//  gitHubApi
//
//  Created by Juan Guillermo Quiroga Salamanca on 11/5/19.
//  Copyright (c) 2019 Juan Guillermo Quiroga Salamanca. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ResultScreenRoutingLogic
{
  //func routeToSomewhere(segue: UIStoryboardSegue?)
    func routeToDetails(segue: UIStoryboardSegue?)
}

protocol ResultScreenDataPassing
{
  var dataStore: ResultScreenDataStore? { get }
}

class ResultScreenRouter: NSObject, ResultScreenRoutingLogic, ResultScreenDataPassing
{
  weak var viewController: ResultScreenViewController?
  var dataStore: ResultScreenDataStore?
  
  // MARK: Routing
  
  func routeToDetails(segue: UIStoryboardSegue?)
  {
    if let segue = segue {
      let destinationVC = segue.destination as! DetailScreenViewController
      var destinationDS = destinationVC.router!.dataStore!
      passDataToSomewhere(source: dataStore!, destination: &destinationDS)
    } else {
      let storyboard = UIStoryboard(name: "Main", bundle: nil)
      let destinationVC = storyboard.instantiateViewController(withIdentifier: "detailScreen") as! DetailScreenViewController
      var destinationDS = destinationVC.router!.dataStore!
      passDataToSomewhere(source: dataStore!, destination: &destinationDS)
      navigateToSomewhere(source: viewController!, destination: destinationVC)
    }
  }

  // MARK: Navigation
  
  func navigateToSomewhere(source: ResultScreenViewController, destination: DetailScreenViewController)
  {
    source.show(destination, sender: nil)
  }
  
  // MARK: Passing data
  
  func passDataToSomewhere(source: ResultScreenDataStore, destination: inout DetailScreenDataStore)
  {
    destination.result = source.result
  }
}
