# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'gitHubApi' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for gitHubApi
	pod 'Alamofire'
	pod 'AlamofireNetworkActivityIndicator', '~> 2.4'

  target 'gitHubApiTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'gitHubApiUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
